### ISSUE TITLE
Script Output

### ISSUE THREAD

**Issue by simzdk** [joshburkard/SCCM#1]
Great script! Is it possible to return the script output from this?

**Comment by joshburkard** [comment]
yes, i will publish a function to get the Script Output in the next week

**Comment by joshburkard** [comment]
now, i published the function Get-SCCMScriptExecutionStatus, which will return the status of a CMscript and the output. please be aware, if the script will run for more than 1 minute, SCCM will return status "Failed" and no output is returned, anyway the script will finish successfull on the client side.
